### ISSUE TITLE
Case-sensitive Mode in Start-SFVolumePairing

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#78] opened 2019-07-30 10:27 UTC
```
PS > Start-SFVolumePairing  -VolumeID 19 -Mode sync -Target 192.168.1.2                
Start-SFVolumePairing : Cannot validate argument on parameter 'Mode'.
The argument "sync" does not belong to the set "Async,Sync,SnapshotsOnly" 
specified by the ValidateSet attribute. Supply an argument that is in the set 
and then try the command again.
 
PS > Start-SFVolumePairing  -VolumeID 19 -Mode Sync -Target 192.168.1.2 

VolumePairingKey
----------------
7....
```
Online help doesn't say anything about case sensitivity and I think our plugin shouldn't care.

```
PARAMETERS
    -Mode <string>
        The mode of the volume on which to start the pairing process.
        
        Required?                    false
        Position?                    1
        Default value                
        Accept pipeline input?       true (ByValue, ByPropertyName)
        Accept wildcard characters?  

```

**Comment by arjun960** [comment] 2022-03-07 22:15
@scaleoutsean The issue is already fixed and is available in the SDK1.7 release.

Hence, closing the issue.

**Closed as completed by arjun960** 2022-03-07 22:15 UTC
