### ISSUE TITLE
Document uninstall (upgrade) procedure for Uninstall-Module

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#37] opened 2017-12-04 02:49 UTC
I didn't have much time to troubleshoot this, but it seems `Uninstall-Module` (including some of it variants/options) doesn't work well. I installed the old way (not with Install-Module) so I guess I should remove manually, install with Install-Module and then Uninstall-Module might work.

```
PS /home/sean> uninstall-module SolidFire                                       
PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'SolidFire'.
At /opt/microsoft/powershell/6.0.0-rc/Modules/PowerShellGet/1.5.0.0/PSModule.psm1:2266 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
+ FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage
```

**Comment by ahaid** [comment] 2017-12-04 03:53
@mblessing Can you attempt to reproduce this and see if @scaleoutsean has other options for removing the SolidFire module?

**Comment by scaleoutsean** [comment] 2017-12-04 04:35
I followed the 1.4 install procedure in reverse (I had to find the old 1.4-tagged install guide), this works fine.
```
$ sudo su
# cd /usr/local/share/powershell/Modules/SolidFire
# ll
total 2388
drwxr-xr-x 2 root root   4096 Nov 25 23:16 ./
drwxr-xr-x 3 root root   4096 Nov 25 22:59 ../
-rw-r--r-- 1 root root   4617 Nov 25 23:16 Initialize-SFEnvironment.ps1
-rw-r--r-- 1 root root 526336 Nov 25 23:00 Newtonsoft.Json.dll
-rw-r--r-- 1 root root 318464 Nov 25 23:00 SolidFire.dll
-rw-r--r-- 1 root root 855303 Nov 25 23:00 SolidFire.dll-help.xml
-rw-r--r-- 1 root root   6728 Nov 25 23:00 SolidFire.psd1
-rw-r--r-- 1 root root 716280 Nov 25 23:00 SolidFire.SDK.dll
# rm -rf Newtonsoft.Json.dll SolidFire.dll SolidFire.dll-help.xml SolidFire.psd1 SolidFire.SDK.dll 
```
Then follow the new Install-Module approach to install v1.5.

**Edit 1:** it works great! I only cannot connect:
```
PS /home/sean> Connect-SFCluster  1.1.1.1 -Username admin -Password password                                                               
Connect-SFCluster : Could not load file or assembly 'System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```
I have Ubuntu 17.10 with 17.04 PS package ([17.10 repo](https://packages.microsoft.com/config/ubuntu/17.10/) exists but it seems it's not yet in CI/CD builds so binaries aren't yet available). I tried to install NuGet first and some other stuff, no difference. My PS version is 6.0 RC1.

**Edit 2:** I installed a fresh Ubuntu 16.04 x64 VM, PS 6.0.0 RC1 and `Install-Module SolidFire` - it still doesn't work. In the meantime, I tried the manual steps from v1.4 - they do work. Something's wrong with the way Install-Module installs SF bits.
https://github.com/solidfire/PowerShell/blob/1.4/docs/linux/README.md#next-install-solidfire-bits

**Edit 3:** https://github.com/solidfire/PowerShell/issues/38 is loosely related to this one. My old init file, which I didn't deleted, was still telling me `Get-SFCommand` is available. Perhaps steps mentioned above should include the removal of Initialize-SFEnvironment.ps1 as well.

**Comment by mblessing** [comment] 2017-12-04 19:31
@scaleoutsean I think the Uninstall-Module cmdlet can only uninstall modules that were originally installed with Install-Module.  The Get-InstalledModule cmdlet will list the modules that it knows about.  I think those are the only ones that can be deleted this way.

This leads to some awkwardness when switching from a manual install technique to using PowerShell Gallery.  I ran into a similar problem with PowerCLI from VMware.

The right thing to do is to uninstall the old version using the old instructions and then install the new version with Install-Module.  After that, managing upgrades and uninstalls should be much easier.

I agree that we should document this.

I am looking into the problem you had with creating the connection and will reply separately about that.

**Comment by mblessing** [comment] 2017-12-04 19:34
@scaleoutsean @ahaid I can duplicate the problem with the missing System.Net.Http.WebRequest assembly when trying to create a connection.  I am doing this on Ubuntu 17.10.  I installed SolidFire 1.5.0.119 using Install-Module.

**Comment by mblessing** [comment] 2017-12-04 20:46
@scaleoutsean @ahaid I see the same error about a missing .NET assembly on the Mac.

**Comment by mblessing** [comment] 2017-12-04 21:06
@scaleoutsean @ahaid Works OK on Windows 10.

**Comment by ahaid** [comment] 2017-12-04 21:08
I'm looking into it. We will probably need to release a hotfix or change the install instructions. I'll know more soon.

**Comment by wesselgans** [comment] 2017-12-11 16:42
Hi,
I have the same issue can't connect to the cluster.
Any thoughts? 
Connect-SFCluster : Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At line:1 char:1
+ Connect-SFCluster 1.1.1.1 -Username 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-SFCluster], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,SolidFire.Connection.ConnectSFCluster

Thanks,
Wessel

**Comment by ahaid** [comment] 2017-12-11 22:59
I have fixed the module for Linux but Mac is proving troublesome. To install the SolidFire module on a Linux machine, use:

    Install-Module SolidFire.Linux

The [installation instructions](https://github.com/solidfire/PowerShell/blob/master/docs/linux/README.md) have been updated in the master branch. 

I'll update this issue again after I get some time to work on the Mac OS installation.

**Comment by scaleoutsean** [comment] 2017-12-12 13:56
Adam's suggestion at first didn't work for me, so I spent 3 hours looking for a workaround... When I was about to post what didn't work and how I give up, I got it to work. 

I think an additional problem in my case - which I discovered at the very end - was that I had some other MS stuff installed and so I entered a Linux version of Windows 3.1 DLL Hell... Once I gave up, purged everything (.NET, SDKs, etc.) to wrap up and was getting ready to submit a summary, it worked. I think one of potential causes is SolidFire.SDK.dll which I had installed from before (see install steps for SolidFire PowerShell Tools v1.4). Until I purged everything else except PS 6.0.0 RC and this module, I was still getting the same DLL error.

**Comment by ahaid** [comment] 2017-12-12 19:24
@scaleoutsean Yeah that's what the OP was concerned with. The process for removing previous versions is unclear. I will edit the readme to include those instructions.

**Comment by ahaid** [comment] 2017-12-12 22:15
We updated the Linux installation page with uninstall and upgrade instructions.

**Comment by ahaid** [comment] 2017-12-12 22:15
Still need to work on the Mac instructions.

**Comment by wesselgans** [comment] 2018-01-26 16:09
Do we have updated instructions for Mac?
Many thanks

**Comment by ahaid** [comment] 2018-01-26 16:12
Not yet. High Sierra has changed the SSL libraries we can use and it's proving difficult. We hope to have this working out by the PowerShell module version 1.6 release.

**Comment by ahaid** [comment] 2018-04-16 16:46
With the 1.5.1 hotfix released last week, this should work now. run `Import-Module SolidFire.Core` to bring in the newest module. More installation instructions are available [here](https://github.com/solidfire/PowerShell/blob/master/docs/linux/README.md).

**Comment by scaleoutsean** [comment] 2018-04-17 12:09
@ahaid, that's great. 
I just looked at v1.5.1 RN's, there's a chapter "Installing or Upgrading" (for Linux), but the readme file talks only about `Install-Module` - there's nothing on upgrading.

As before, when we had SolidFire and the new name was SolidFire.Linux, now we have SolidFire.Linux and the new module name is SolidFire.Core, so the upgrade ambiguity remains.

As root user I tried to `Import-Module SolidFire.Linux` and then `Remove-Module SolidFire.Linux` and I couldn't do it (error that the module is in use whereas it wasn't in use, it was just loaded). I had to use `-Force` to unload the module.

Then I used `Uninstall-Module SolidFire.Linux` followed by `Install-Module SolidFire.Core` to install v1.5.1.1...  I didn't try to install SolidFire.Core without un-installing SolidFire.Linux, because I don't want to risk ending up with 2 conflicting modules. This is on Ubuntu 16.04.

**UPDATE**

Interestingly, on CentOS 7.4 and with PS  v6.1.0-preview.1, our SolidFire module v1.5.0 isn't cold SolidFire.Linux, but SolidFire, so on CentOS/RHEL it has to be uninstalled with `Remove-Module SolidFire`.

```
PS /root> Get-Module -ListAvailable

    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.5.0.119  SolidFire            
```
In v1.5.1.1, there's no such issue:

```
PS /root> Get-Module -ListAvailable -Refresh                                                                                                                                                                                                        Directory: /usr/local/share/powershell/Modules                                                                                                              

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.5.1.1    SolidFire.Core

**Comment by arjun960** [comment] 2021-09-20 16:41
As per the above conversation, the instructions for "Installing or Upgrading" is updated for Linux. 

The following statements are applicable to powershell version >6.0 (if you are using powershell <6, please upgrade to latest version of powershell to use the latest feature of powershell and get latest solidifre powershell sdk to work on latest cluster apis install SolidFire.Core Module 12.3):
For installing latest version of SolidFire Powershell Module on Operating Systems ("Windows" , "Mac", "Linux" ) you can run the commandlet "Install-Module SolidFire.Core".
For upgrading to the latest version of SolidFire Powershell Module on Operating Systems ("Windows", "Mac", "Linux") you can run "Install-Module SolidFire.Core -Force".
For Uninstalling Solidfire Powershell Module on Operating systems ("Windows", "Mac", "Linux") you can run "Uninstall-Module SolidFire.Core". Suppose you have initially installed SDK 1.7 and upgraded to SDK 12.3, running uninstall module will only uninstall SDK 12.3 but not SDK 1.7, you have to run Uninstall command again to uninstall 1.7.

To uninstall all versions of Solidfire powershell module at once run "Uninstall-Module SolidFire.Core -AllVersions".

And as stated above, yes uninstalling of powershell modules using Uninstall-Module commandlet works only if the module is installed through "Install-Module" Commandlet or if the respective module files are placed in the correct Powershell Modules folder. 

Hope this information answers your query. Closing the issue as the issue is resolved.

**Closed as completed by arjun960** 2021-09-20 16:41 UTC
