### ISSUE TITLE
Remove-SFInitiatorFromVolumeAccessGroup removes the initiator from the cluster altogether (rather than just from the access group)

### ISSUE THREAD

**Issue by ddansf** [solidfire/PowerShell#75] opened 2019-05-09 20:50 UTC
**Observed in:**

Powershell module 1.5.0.119 on a cluster on Element OS 11.0

**Description of cmdlet:**

NAME
    Remove-SFInitiatorFromVolumeAccessGroup
 
SYNOPSIS
    [Cluster] Removes initiators from a volume access group.

**Example Command:**

Remove-SFInitiatorFromVolumeAccessGroup -VolumeAccessGroupID <A> -Initiators <iqn.xxx.yyyyy:zzzzz>

**Expected Result:**

Initiator <iqn.xxx.yyyyy:zzzzz> is removed from Volume Access Group <A>, but still exists on the cluster.

**Actual Result:**

Initiator <iqn.xxx.yyyyy:zzzzz> is removed from Volume Access Group <A>, and is also deleted from the cluster altogether.

**Comment by scaleoutsean** [comment] 2019-08-30 13:30
Interesting bug. 

> Expected Result:
> Initiator iqn.xxx.yyyyy:zzzzz is removed from Volume Access Group , but still exists on the cluster.

According to the API guide `deleteOrphanInitiators` defaults to `true`, so I would say expected result is that the IQN(s) get wiped, but the problem is that the parameter isn't implemented (and/or documented in PowerShell Tools). 

A workaround is to use `Invoke-SFApi` with `ModifyVolumeAccessGroup` and make sure "orphaned" initiators don't get wiped. 

The UI defaults to `deleteOrphanInitiators:$false`, which is different from the API. This issue should be fixed because this behavior is undocumented in SF PS Tools and produces rather unexpected results (not everyone reads the SDK before they use SF PS Tools, I certainly don't).

**Comment by ntavendale** [comment] 2020-01-17 17:39
Next version of PS will have an optional parameter -DeleteOrphanInitiators which, if not used, will default to false, consistent with UI.

**Closed as completed by ntavendale** 2020-01-17 17:39 UTC
